name: "ğŸ¯ Pushed"

on:
  push:
    branches:
      - '*'
  pull_request:  # ãƒ—ãƒ«ãƒªã‚¯ã‚¨ã‚¹ãƒˆã«åå¿œ
    types: [opened, synchronize]  # ãƒ—ãƒ«ãƒªã‚¯ã‚¨ã‚¹ãƒˆãŒã‚ªãƒ¼ãƒ—ãƒ³ã€æ›´æ–°ã•ã‚ŒãŸå ´åˆã«ãƒˆãƒªã‚¬ãƒ¼

jobs:
  test:
    name: 'âœ… ãƒ†ã‚¹ãƒˆ'
    uses: ./.github/workflows/_test.yml
    with:
      python-version: '3.11'

  check-lint:
    name: 'âœ… ãƒªãƒ³ãƒˆãƒã‚§ãƒƒã‚¯'
    uses: ./.github/workflows/_lint-check.yml
    with:
      python-version: '3.11'

  check-format:
    name: 'âœ… ãƒ•ã‚©ãƒ¼ãƒãƒƒãƒˆãƒã‚§ãƒƒã‚¯'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "WIP"
