name: "ğŸ¯ Pushed"

on:
  push:  # ãƒ—ãƒƒã‚·ãƒ¥ã«åå¿œ
    branches:
      - '*'  # å…¨ãƒ–ãƒ©ãƒ³ãƒã¸ã®pushã«åå¿œ
  pull_request:  # ãƒ—ãƒ«ãƒªã‚¯ã‚¨ã‚¹ãƒˆã«åå¿œ
    types: [opened, synchronize]  # ãƒ—ãƒ«ãƒªã‚¯ã‚¨ã‚¹ãƒˆãŒã‚ªãƒ¼ãƒ—ãƒ³ã€æ›´æ–°ã•ã‚ŒãŸå ´åˆã«ãƒˆãƒªã‚¬ãƒ¼

jobs:
  test:
    name: 'âœ… ãƒ†ã‚¹ãƒˆ'
    uses: ./.github/workflows/_test.yml
    with:
      python-version: '3.12'

  check-code:
    name: 'âœ… ã‚³ãƒ¼ãƒ‰ãƒã‚§ãƒƒã‚¯'
    uses: ./.github/workflows/_check-code.yml
    with:
      python-version: '3.12'
      allow-autocommit: false
